name: QMK Build

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install QMK CLI
        run: |
          python -m pip install --upgrade pip
          python -m pip install qmk

      - name: Install build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc-avr avr-libc avrdude \
            gcc-arm-none-eabi binutils-arm-none-eabi \
            clang-format \
            dfu-programmer dfu-util \
            libusb-1.0-0-dev \
            make git

      - name: QMK build (ohropax_keyboard:default)
        run: |
          qmk build -kb ohropax_keyboard -km default
